"""
Response Formatter

Converts GenerationResponse into the final user-facing text.

Responsibilities
----------------
- Format recommendations
- Format comparison
- Format clarification
- Include verification notes
"""

from __future__ import annotations

from app.generation.response import (
    FinalResponse,
    GenerationResponse,
)


class ResponseFormatter:
    """
    Converts GenerationResponse into the final response returned
    by the API.

    The frontend is responsible for rendering recommendation
    cards, so this formatter only returns the natural-language
    summary generated by the LLM.
    """

    # --------------------------------------------------

    def format(
        self,
        response: GenerationResponse,
    ) -> FinalResponse:
        """
        Convert GenerationResponse into FinalResponse.
        """

        # --------------------------------------------------
        # Clarification
        # --------------------------------------------------

        if response.clarification is not None:

            return FinalResponse(

                message=response.clarification.question,

                verified=True,

            )

        # --------------------------------------------------
        # Comparison
        # --------------------------------------------------

        if response.comparison is not None:

            comparison = response.comparison

            return FinalResponse(

                message=comparison.summary,

                citations=[

                    comparison.left.url,

                    comparison.right.url,

                ],

                verified=True,

            )

        # --------------------------------------------------
        # Recommendations
        # --------------------------------------------------

        return FinalResponse(

            message=self._format_recommendations(

                response

            ),

            recommendations=response.recommendations,

            citations=response.citations,

            verified=response.verified,

        )

    # --------------------------------------------------

    def _format_recommendations(
        self,
        response: GenerationResponse,
    ) -> str:
        """
        Build the textual recommendation summary.

        Recommendation cards are rendered separately by the
        frontend, so only the LLM summary and verification
        warnings are returned here.
        """

        sections = []

        if response.answer:

            sections.append(

                response.answer.strip()

            )

        if response.warnings:

            if sections:

                sections.append("")

            sections.append("### Notes")

            for warning in response.warnings:

                sections.append(

                    f"- {warning}"

                )

        return "\n".join(sections).strip()